name: Test

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:

  test:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-22.04-arm]
        python: ["3.11", "3.12"]
        cython: ["3.0.12", "3.1.2"]
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: |
          python -m pip install cython==${{ matrix.cython }} numpy pytest setuptools
      - name: Run test
        run: |
          python -m pytest
